"""reset_aware_identity

Revision ID: 08651b9459b7
Revises: cdf8921c6934
Create Date: 2026-07-16 18:17:08.845823

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08651b9459b7'
down_revision: Union[str, Sequence[str], None] = 'cdf8921c6934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_key', sa.String(), nullable=False),
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('log_scope', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_index', sa.String(), nullable=True),
    sa.Column('caused_by', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('lifecycle_status', sa.String(), nullable=False),
    sa.Column('known_issue_id', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('ticket_link', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('severity_override', sa.String(), nullable=True),
    sa.Column('suppression_override', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_series'))
    )
    with op.batch_alter_table('alert_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_series_alert_key'), ['alert_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_alert_series_id'), ['id'], unique=False)

    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ingested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source_filename', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_generated_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_state_file', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_file_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('raw_signed_delta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interval_delta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interval_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rate_per_hour', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('counter_reset_detected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('counter_epoch', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data_quality_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.alter_column('red_threshold',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_index('ix_alert_events_fpexact_observed_at', ['fingerprint_exact', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_series_id'), ['series_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_alert_events_series_id_alert_series'), 'alert_series', ['series_id'], ['id'])

    # ### end Alembic commands ###

    _backfill_alert_series()


def _backfill_alert_series() -> None:
    """One-time data migration (not autogenerated): create one AlertSeries
    per distinct fingerprint_exact already in alert_events, seeded from that
    alert_key's most-recent row (owner/ticket/notes/known_issue_id) and the
    min/max of first_seen/last_seen across all its rows, then point every
    existing alert_events row at its series. Safe to run once; alert_events
    rows are read-only here (only series_id is set), nothing is deleted."""
    conn = op.get_bind()
    alert_events = sa.table(
        "alert_events",
        sa.column("id", sa.Integer),
        sa.column("fingerprint_exact", sa.String),
        sa.column("tenant", sa.String),
        sa.column("system", sa.String),
        sa.column("hostname", sa.String),
        sa.column("log_file", sa.String),
        sa.column("error_type", sa.String),
        sa.column("error_index", sa.String),
        sa.column("caused_by", sa.String),
        sa.column("first_seen", sa.String),
        sa.column("last_seen", sa.String),
        sa.column("known_issue_id", sa.String),
        sa.column("owner", sa.String),
        sa.column("ticket_link", sa.String),
        sa.column("notes", sa.Text),
        sa.column("created_at", sa.DateTime),
        sa.column("series_id", sa.Integer),
    )
    alert_series = sa.table(
        "alert_series",
        sa.column("id", sa.Integer),
        sa.column("alert_key", sa.String),
        sa.column("tenant", sa.String),
        sa.column("system", sa.String),
        sa.column("hostname", sa.String),
        sa.column("log_scope", sa.String),
        sa.column("error_type", sa.String),
        sa.column("error_index", sa.String),
        sa.column("caused_by", sa.String),
        sa.column("first_seen", sa.DateTime),
        sa.column("last_seen", sa.DateTime),
        sa.column("lifecycle_status", sa.String),
        sa.column("known_issue_id", sa.String),
        sa.column("owner", sa.String),
        sa.column("ticket_link", sa.String),
        sa.column("notes", sa.Text),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )

    rows = conn.execute(
        sa.select(
            alert_events.c.id,
            alert_events.c.fingerprint_exact,
            alert_events.c.tenant,
            alert_events.c.system,
            alert_events.c.hostname,
            alert_events.c.log_file,
            alert_events.c.error_type,
            alert_events.c.error_index,
            alert_events.c.caused_by,
            alert_events.c.first_seen,
            alert_events.c.last_seen,
            alert_events.c.known_issue_id,
            alert_events.c.owner,
            alert_events.c.ticket_link,
            alert_events.c.notes,
            alert_events.c.created_at,
        )
        .where(alert_events.c.fingerprint_exact.isnot(None))
        .order_by(alert_events.c.fingerprint_exact, alert_events.c.created_at.asc())
    ).fetchall()

    def _parse_iso(value):
        if not value:
            return None
        try:
            return datetime.fromisoformat(value)
        except ValueError:
            return None

    groups: dict = {}
    for row in rows:
        groups.setdefault(row.fingerprint_exact, []).append(row)

    now = datetime.utcnow()
    for key, group_rows in groups.items():
        latest = group_rows[-1]  # ascending by created_at, so last = most recent
        first_seen_values = [d for d in (_parse_iso(r.first_seen) for r in group_rows) if d]
        last_seen_values = [d for d in (_parse_iso(r.last_seen) for r in group_rows) if d]

        conn.execute(
            alert_series.insert().values(
                alert_key=key,
                tenant=latest.tenant,
                system=latest.system,
                hostname=latest.hostname,
                log_scope=latest.log_file,
                error_type=latest.error_type,
                error_index=latest.error_index,
                caused_by=latest.caused_by,
                first_seen=min(first_seen_values) if first_seen_values else None,
                last_seen=max(last_seen_values) if last_seen_values else None,
                lifecycle_status="active",
                known_issue_id=latest.known_issue_id,
                owner=latest.owner,
                ticket_link=latest.ticket_link,
                notes=latest.notes,
                created_at=now,
                updated_at=now,
            )
        )
        # `alert_series` is a lightweight sa.table() (no primary-key metadata),
        # so Core's inserted_primary_key isn't available here — alert_key is
        # unique, so querying it back is a simple, portable way to get the id.
        series_id = conn.execute(
            sa.select(alert_series.c.id).where(alert_series.c.alert_key == key)
        ).scalar_one()

        ids = [r.id for r in group_rows]
        conn.execute(
            alert_events.update().where(alert_events.c.id.in_(ids)).values(series_id=series_id)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alert_events_series_id_alert_series'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alert_events_series_id'))
        batch_op.drop_index('ix_alert_events_fpexact_observed_at')
        batch_op.alter_column('red_threshold',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('series_id')
        batch_op.drop_column('data_quality_status')
        batch_op.drop_column('counter_epoch')
        batch_op.drop_column('counter_reset_detected')
        batch_op.drop_column('rate_per_hour')
        batch_op.drop_column('interval_seconds')
        batch_op.drop_column('interval_delta')
        batch_op.drop_column('raw_signed_delta')
        batch_op.drop_column('source_file_hash')
        batch_op.drop_column('source_state_file')
        batch_op.drop_column('source_generated_time')
        batch_op.drop_column('source_filename')
        batch_op.drop_column('ingested_at')
        batch_op.drop_column('observed_at')

    with op.batch_alter_table('alert_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_series_id'))
        batch_op.drop_index(batch_op.f('ix_alert_series_alert_key'))

    op.drop_table('alert_series')
    # ### end Alembic commands ###
