"""data_quality_and_resolution_grace

Revision ID: 2c792ec8b9a4
Revises: 08651b9459b7
Create Date: 2026-07-17 00:30:00.959229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c792ec8b9a4'
down_revision: Union[str, Sequence[str], None] = '08651b9459b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_resolution_since', sa.DateTime(), nullable=True))
        # server_default backfills existing rows — SQLite refuses to add a
        # NOT NULL column with no default to a table that already has rows.
        batch_op.add_column(sa.Column('absence_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('prom_snapshot_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('invalid_row_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('duplicate_row_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('parse_warnings', sa.Text(), nullable=True))

    with op.batch_alter_table('prom_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completeness_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('missing_files', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('newly_discovered_files', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prom_snapshots', schema=None) as batch_op:
        batch_op.drop_column('newly_discovered_files')
        batch_op.drop_column('missing_files')
        batch_op.drop_column('completeness_status')

    with op.batch_alter_table('prom_snapshot_files', schema=None) as batch_op:
        batch_op.drop_column('parse_warnings')
        batch_op.drop_column('duplicate_row_count')
        batch_op.drop_column('invalid_row_count')
        batch_op.drop_column('quality_status')

    with op.batch_alter_table('alert_series', schema=None) as batch_op:
        batch_op.drop_column('absence_count')
        batch_op.drop_column('pending_resolution_since')

    # ### end Alembic commands ###
