"""baseline

Revision ID: cdf8921c6934
Revises: 
Create Date: 2026-07-16 18:16:51.163583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf8921c6934'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('received_time', sa.String(), nullable=True),
    sa.Column('received_time_display', sa.String(), nullable=True),
    sa.Column('total_issues_detected', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_batches'))
    )
    with op.batch_alter_table('alert_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_batches_batch_id'), ['batch_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_alert_batches_id'), ['id'], unique=False)

    op.create_table('known_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('known_issue_id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('host_scope', sa.String(), nullable=True),
    sa.Column('log_scope', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('normal_count_min', sa.Integer(), nullable=True),
    sa.Column('normal_count_max', sa.Integer(), nullable=True),
    sa.Column('normal_growth_min', sa.Integer(), nullable=True),
    sa.Column('normal_growth_max', sa.Integer(), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('resolution_steps', sa.Text(), nullable=True),
    sa.Column('runbook_link', sa.String(), nullable=True),
    sa.Column('ticket_link', sa.String(), nullable=True),
    sa.Column('last_reviewed', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_known_issues'))
    )
    with op.batch_alter_table('known_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_known_issues_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_issues_known_issue_id'), ['known_issue_id'], unique=True)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('raw_filename', sa.String(), nullable=True),
    sa.Column('log_file', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('growth', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('first_seen', sa.String(), nullable=True),
    sa.Column('last_seen', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('fingerprint_exact', sa.String(), nullable=True),
    sa.Column('fingerprint_general', sa.String(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('known_issue_id', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('runbook_link', sa.String(), nullable=True),
    sa.Column('ticket_link', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('normal_range', sa.String(), nullable=True),
    sa.Column('escalation_rule', sa.String(), nullable=True),
    sa.Column('system_type', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('error_index', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('raw_known_error', sa.String(), nullable=True),
    sa.Column('raw_note', sa.String(), nullable=True),
    sa.Column('caused_by', sa.String(), nullable=True),
    sa.Column('previous_count', sa.Integer(), nullable=True),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('is_red', sa.Boolean(), nullable=True),
    sa.Column('red_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['alert_batches.batch_id'], name=op.f('fk_alert_events_batch_id_alert_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_alert_id'), ['alert_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_alert_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_fingerprint_exact'), ['fingerprint_exact'], unique=False)
        batch_op.create_index('ix_alert_events_fpexact_processed_at', ['fingerprint_exact', 'processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('prom_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('source_mode', sa.String(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('file_modified_time', sa.String(), nullable=True),
    sa.Column('processed_at', sa.String(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('total_metrics', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['alert_batches.batch_id'], name=op.f('fk_prom_snapshots_batch_id_alert_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prom_snapshots'))
    )
    with op.batch_alter_table('prom_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prom_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prom_snapshots_snapshot_id'), ['snapshot_id'], unique=True)

    op.create_table('alert_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_event_id', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.alert_id'], name=op.f('fk_alert_notes_alert_event_id_alert_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_notes'))
    )
    with op.batch_alter_table('alert_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_notes_alert_event_id'), ['alert_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_notes_id'), ['id'], unique=False)

    op.create_table('issue_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_event_id', sa.String(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.alert_id'], name=op.f('fk_issue_status_history_alert_event_id_alert_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_status_history'))
    )
    with op.batch_alter_table('issue_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_status_history_alert_event_id'), ['alert_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_status_history_id'), ['id'], unique=False)

    op.create_table('prom_snapshot_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('file_modified_time', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('metric_count', sa.Integer(), nullable=True),
    sa.Column('generated_time', sa.String(), nullable=True),
    sa.Column('state_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['prom_snapshots.snapshot_id'], name=op.f('fk_prom_snapshot_files_snapshot_id_prom_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prom_snapshot_files'))
    )
    with op.batch_alter_table('prom_snapshot_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prom_snapshot_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prom_snapshot_files_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prom_snapshot_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prom_snapshot_files_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_prom_snapshot_files_id'))

    op.drop_table('prom_snapshot_files')
    with op.batch_alter_table('issue_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_status_history_id'))
        batch_op.drop_index(batch_op.f('ix_issue_status_history_alert_event_id'))

    op.drop_table('issue_status_history')
    with op.batch_alter_table('alert_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_notes_id'))
        batch_op.drop_index(batch_op.f('ix_alert_notes_alert_event_id'))

    op.drop_table('alert_notes')
    with op.batch_alter_table('prom_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prom_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_prom_snapshots_id'))

    op.drop_table('prom_snapshots')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_signal_type'))
        batch_op.drop_index(batch_op.f('ix_alert_events_id'))
        batch_op.drop_index('ix_alert_events_fpexact_processed_at')
        batch_op.drop_index(batch_op.f('ix_alert_events_fingerprint_exact'))
        batch_op.drop_index(batch_op.f('ix_alert_events_batch_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_alert_id'))

    op.drop_table('alert_events')
    with op.batch_alter_table('known_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_known_issues_known_issue_id'))
        batch_op.drop_index(batch_op.f('ix_known_issues_id'))

    op.drop_table('known_issues')
    with op.batch_alter_table('alert_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_batches_id'))
        batch_op.drop_index(batch_op.f('ix_alert_batches_batch_id'))

    op.drop_table('alert_batches')
    # ### end Alembic commands ###
